theme:
  error_border: "237, 135, 150" # error dialog border is Red
  error_text: "238, 153, 160" # error message text (e.g. "Spotify API reported error 404") is Maroon
  hint: "238, 212, 159" # hint text in errors Yellow
  playbar_background: "24, 25, 38" # background of progress bar "Crust"
  playbar_progress: "30, 32, 48" # filled-in part of the progress bar Mantle
  playbar_progress_text: "166, 218, 149" # song length and time played/left indicator in the progress bar "Green"
  playbar_text: "165, 173, 203" # artist name in player pane is "Subtext 0"
  inactive: "110, 115, 141" # borders of inactive panes "Overlay 0"
  text: "202, 211, 245" # text in panes is "Text"
  active: "198, 160, 246" # current playing song in list Mauve
  banner: "139, 213, 202" # the "spotify-tui" banner on launch Teal
  hovered: "245, 189, 230" # hovered pane border Pink
  selected: "183, 189, 248" # a) selected pane border, b) hovered item in list, & c) track title in player Lavender
  header: "183, 189, 248" # header text in panes (e.g. 'Title', 'Artist', etc.) Lavender

behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  # The lower the number the higher the "frames per second". You can decrease this number so that the audio visualisation is smoother but this can be expensive!
  tick_rate_milliseconds: 250
  # Enable text emphasis (typically italic/bold text styling). Disabling this might be important if the terminal config is otherwise restricted and rendering text escapes interferes with the UI.
  enable_text_emphasis: true
  # Controls whether to show a loading indicator in the top right of the UI whenever communicating with Spotify API
  show_loading_indicator: true
  # Disables the responsive layout that makes the search bar smaller on bigger
  # screens and enforces a wide search bar
  enforce_wide_search_bar: false
  # Determines the text icon to display next to "liked" Spotify items, such as
  # liked songs and albums, or followed artists. Can be any length string.
  # These icons require a patched nerd font.
  liked_icon: ♥
  shuffle_icon: 🔀
  repeat_track_icon: 🔂
  repeat_context_icon: 🔁
  playing_icon: ▶
  paused_icon: ⏸
  # Sets the window title to "spt - Spotify TUI" via ANSI escape code.
  set_window_title: true


keybindings:
  # Key stroke can be used if it only uses two keys:
  # ctrl-q works,
  # ctrl-alt-q doesn't.
  back: "ctrl-q"

  jump_to_album: "a"

  # Shift modifiers use a capital letter (also applies with other modifier keys
  # like ctrl-A)
  jump_to_artist_album: "A"

  manage_devices: "d"
  decrease_volume: "-"
  increase_volume: "+"
  toggle_playback: " "
  seek_backwards: "<"
  seek_forwards: ">"
  next_track: "n"
  previous_track: "p"
  copy_song_url: "c"
  copy_album_url: "C"
  help: "?"
  shuffle: "ctrl-s"
  repeat: "r"
  search: "/"
  audio_analysis: "v"
  jump_to_context: "o"
  basic_view: "B"
  add_item_to_queue: "z"
